// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnwegxciqsyfzfkerswc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impud2VneGNpcXN5Znpma2Vyc3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODg4ODQsImV4cCI6MjA2MTY2NDg4NH0.FY_zWXZ-TbqooM0OZpJyTB98YURaxztyHzuwWaH3vU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);